# Generated by Django 4.1 on 2022-09-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
